function f = showattributeinfowindow(MatParMatrix,f,chi2)
    position = [50, 300, 300, 210];
    position_layer1 = [5, 0, 100, 170];
    position_layer2 = [105, 0, 100, 170];
    position_layer3 = [205, 0, 100, 170];
    position_text = [5, 197, 300, 10];
    position_bm = [5, 177, 300, 8];
    if(f == 0)
        f=dialog('Name','Simulation Attributes','Units','points','Position',position,'WindowStyle','normal','Toolbar','none',...
                 'DockControls','off','MenuBar','none','Resize','off','ToolBar','none',...
                 'NumberTitle','off');
    end
    bm = strcat('Bestimmtheitsmass =  ',num2str(chi2));
    text=uicontrol(f,'Style','text','Units','points','Position',position_text,'String','shows Attributes of the last simulation step',...
                   'Tag','MessageBox','HorizontalAlignment','left','FontSize',10);
    bm=uicontrol(f,'Style','text','Units','points','Position',position_bm,'String',bm,...
                   'Tag','MessageBox','HorizontalAlignment','left','FontSize',8);
    layer1=uicontrol(f,'Style','text','Units','points','Position',position_layer1,'String',' ',...
                   'Tag','MessageBox','HorizontalAlignment','left','FontSize',8);
    layer2=uicontrol(f,'Style','text','Units','points','Position',position_layer2,'String',' ',...
                   'Tag','MessageBox','HorizontalAlignment','left','FontSize',8);
    layer3=uicontrol(f,'Style','text','Units','points','Position',position_layer3,'String',' ',...
                   'Tag','MessageBox','HorizontalAlignment','left','FontSize',8);
   
              
    a = {'Layer1' '' num2str(MatParMatrix(1,1),'%g') num2str(MatParMatrix(2,1),'%g') num2str(MatParMatrix(3,1),'%g') num2str(MatParMatrix(4,1),'%g') ...
        num2str(MatParMatrix(5,1),'%g') num2str(MatParMatrix(6,1),'%g') num2str(MatParMatrix(7,1),'%g') num2str(MatParMatrix(8,1),'%g') ...
        num2str(MatParMatrix(9,1),'%g') num2str(MatParMatrix(10,1),'%g') num2str(MatParMatrix(11,1),'%g') num2str(MatParMatrix(12,1),'%g') ...
        num2str(MatParMatrix(13,1),'%g') num2str(MatParMatrix(14,1),'%g')}';
    
   if(exist('MatParMatrix(1,2)') == 1)
        b = {'Layer2' '' num2str(MatParMatrix(1,2),'%g') num2str(MatParMatrix(2,2),'%g') num2str(MatParMatrix(3,2),'%g') num2str(MatParMatrix(4,2),'%g') ...
            num2str(MatParMatrix(5,2),'%g') num2str(MatParMatrix(6,2),'%g') num2str(MatParMatrix(7,2),'%g') num2str(MatParMatrix(8,2),'%g') ...
            num2str(MatParMatrix(9,2),'%g') num2str(MatParMatrix(10,2),'%g') num2str(MatParMatrix(11,2),'%g') num2str(MatParMatrix(12,2),'%g') ...
            num2str(MatParMatrix(13,2),'%g') num2str(MatParMatrix(14,2),'%g')}';
    else b = '';
    end
    if(exist('MatParMatrix(1,3)') == 1)
        c = {'Layer3' '' num2str(MatParMatrix(1,3),'%g') num2str(MatParMatrix(2,3),'%g') num2str(MatParMatrix(3,3),'%g') num2str(MatParMatrix(4,3),'%g') ...
            num2str(MatParMatrix(5,3),'%g') num2str(MatParMatrix(6,3),'%g') num2str(MatParMatrix(7,3),'%g') num2str(MatParMatrix(8,3),'%g') ...
            num2str(MatParMatrix(9,3),'%g') num2str(MatParMatrix(10,3),'%g') num2str(MatParMatrix(11,3),'%g') num2str(MatParMatrix(12,3),'%g') ...
            num2str(MatParMatrix(13,3),'%g') num2str(MatParMatrix(14,3),'%g')}';
    else c = '';
    end
    set(layer1,'String',a);
    set(layer2,'String',b);
    set(layer3,'String',c);